# Generated by Django 2.2 on 2019-05-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190514_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('2', '매우중요'), ('0', '보통'), ('1', '중요')], default=0, max_length=1),
        ),
    ]
