# Generated by Django 2.2 on 2019-05-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190514_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('0', '보통'), ('2', '매우중요'), ('1', '중요')], default=0, max_length=1),
        ),
    ]
